---
- name: Use Homebrew Git binary
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsGitBinary
    type: string
    value: /usr/local/bin/git
  when: '"tower" in homebrew_cask_apps and "curl" in homebrew_installed_packages'
  tags: ['homebrew']

- name: Creates default directory for cloned projects
  file: path=${HOME}/Developer state=directory
  when: '"tower" in homebrew_cask_apps'
  tags: ['homebrew']

- name: Set default directory for cloned projects
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsDefaultCloningDirectory
    type: string
    value: ${HOME}/Developer
  when: '"tower" in homebrew_cask_apps'
  tags: ['homebrew']

- name: Check if Kaleidoscope is installed
  stat: path=/Applications/Kaleidoscope.app
  register: kaleidoscope_check
  when: '"tower" in homebrew_cask_apps'
  tags: ['homebrew']

- name: Set diff tool
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsDiffToolIdentifier
    type: string
    value: kaleidoscope
  when: '"tower" in homebrew_cask_apps and kaleidoscope_check.stat.exists == True'
  tags: ['homebrew']

- name: Check if P4Merge is installed
  stat: path=/Applications/p4merge.app
  register: p4merge_check
  when: '"tower" in homebrew_cask_apps'
  tags: ['homebrew']

- name: Set merge tool
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsMergeToolIdentifier
    type: string
    value: p4merge
  when: '"tower" in homebrew_cask_apps and p4merge_check.stat.exists == True'
  tags: ['homebrew']
