---
- name: Ensure location for incomplete downloads exists
  file:
    path: "{{ ansible_env.HOME }}/Downloads/Torrents/Incomplete"
    state: directory
    follow: yes
  when: '"transmission" in homebrew_cask_apps'
  tags: ['homebrew']

- name: Keep incomplete downloads
  osx_defaults:
    domain: org.m0k.transmission
    key: UseIncompleteDownloadFolder
    type: bool
    value: true
  when: '"transmission" in homebrew_cask_apps'
  tags: ['homebrew']

- name: Set path for incomplete downloads
  osx_defaults:
    domain: org.m0k.transmission
    key: IncompleteDownloadFolder
    type: string
    value: "${HOME}/Downloads/Torrents/Incomplete"
  when: '"transmission" in homebrew_cask_apps'
  tags: ['homebrew']

- name: Set path for downloads
  osx_defaults:
    domain: org.m0k.transmission
    key: NSNavLastRootDirectory
    type: string
    value: "${HOME}/Downloads/Torrents"
  when: '"transmission" in homebrew_cask_apps'
  tags: ['homebrew']

- name: "{{ item.name }}"
  osx_defaults:
    domain: org.m0k.transmission
    key: "{{ item.key }}"
    type: bool
    value: "{{ item.value }}"
  with_items:
    - { name: "Don't prompt for confirmation before downloading", key: "DownloadAsk", value: "false"}
    - { name: "Trash original torrent files", key: "DeleteOriginalTorrent", value: "true"}
    - { name: "Hide the donate message", key: "WarningDonate", value: "false"}
    - { name: "Hide the legal disclaimer", key: "WarningLegal", value: "false"}
  when: '"transmission" in homebrew_cask_apps'
  tags: ['homebrew']
