---

- name: Hide Holidays calendar
  osx_defaults:
    domain: com.apple.iCal
    key: "add holiday calendar"
    type: int
    value: 0
  notify:
    - killall Calendar

- name: Hide Birthdays calendar
  osx_defaults:
    domain: com.apple.iCal
    key: "display birthdays calendar"
    type: int
    value: 0
  notify:
    - killall Calendar

- name: Hide Found in Mail calendar
  osx_defaults:
    domain: com.apple.suggestions
    key: SuggestionsShowEventsFoundInMail
    type: int
    value: 0
  notify:
    - killall Calendar

- name: Show sidebar
  osx_defaults:
    domain: com.apple.iCal
    key: CalendarSidebarShown
    type: int
    value: 1
  notify:
    - killall Calendar
