---

- name: Prevent Time Machine from prompting to use new hard drives as backup volume
  osx_defaults:
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true
  notify:
    - killall
