---

os: osx
sudo: required

matrix:
  include:
    # macOS 10.12
    - osx_image: xcode8.2
      env: TAGS=prep
    - osx_image: xcode8.2
      env: TAGS=stage_1
    - osx_image: xcode8.2
      env: TAGS=stage_2
    - osx_image: xcode8.2
      env: TAGS=stage_3
    - osx_image: xcode8.2
      env: TAGS=stage_4
    # macOS 10.11
    - osx_image: xcode8
      env: TAGS=prep
    - osx_image: xcode8
      env: TAGS=stage_1
    - osx_image: xcode8
      env: TAGS=stage_2
    - osx_image: xcode8
      env: TAGS=stage_3
    - osx_image: xcode8
      env: TAGS=stage_4
  fast_finish: true

install:
  - pip install pexpect
  # Debug info
  - python --version
  # Run setup script
  - bash init.sh
  # Debug info
  - pip --version
  - ansible --version

script:
  # Playbook syntax check
  - ansible-playbook mac.yml --syntax-check
  # Run Ansible playbook:
  # - Skip tasks/roles that we know cause issues in Travis
  - ansible-playbook mac.yml --tags "$TAGS" --skip-tags "no_ci,mas_app"