---

os: osx
sudo: required

matrix:
  include:
    # macOS 10.12
    - osx_image: xcode8.3
    # macOS 10.11
    - osx_image: xcode8
  fast_finish: true

install:
  - pip install pexpect
  # Debug info
  - python --version
  # Run setup script
  - bash install-deps.sh
  # Debug info
  - pip --version
  - ansible --version

script:
  # Playbook syntax check
  - ansible-playbook main.yml -i inventory --syntax-check
  # Run Ansible playbook:
  # - Skip tasks/roles that we know cause issues in Travis
  - ansible-playbook main.yml -i inventory --extra-vars "@test.config.json" --skip-tags "skip_ci,xcode"
