---

env:
  - TAGS=prep       SKIP_TAGS=no_ci,mas,mas_app,xcode,swiftlint
  - TAGS=stage_1    SKIP_TAGS=no_ci,mas,mas_app,xcode,swiftlint
  - TAGS=stage_2    SKIP_TAGS=no_ci,mas,mas_app,xcode,swiftlint
  - TAGS=stage_3    SKIP_TAGS=no_ci,mas,mas_app,xcode,swiftlint
  - TAGS=stage_4    SKIP_TAGS=no_ci,mas,mas_app,xcode,swiftlint

matrix:
  include:
    # macOS 10.12
    - os: osx
      osx_image: xcode8.2
      sudo: required
      
    # macOS 10.11
    - os: osx
      osx_image: xcode8
      sudo: required
  fast_finish: true

install:
  - pip install pexpect
  # Debug info
  - python --version
  # Run setup script
  - bash init.sh
  # Debug info
  - pip --version
  - ansible --version

script:
  # Playbook syntax check
  - ansible-playbook mac.yml --syntax-check
  # Run Ansible playbook:
  # - Skip tasks/roles that we know cause issues in Travis
  - ansible-playbook mac.yml --tags "$TAGS" --skip-tags "$SKIP_TAGS"