---

# Override default role variables here.

# homebrew
# ------------------------------------------------------------------------------
homebrew_taps:
  - vapor/tap

atom_upgrade_packages: true
atom_packages:
  # General
  - editorconfig
  # - sync-settings
  # - sort-lines
  # - highlight-selected
  - pigments

  # IDE
  - atom-ide-ui
  # - ide-flowtype
  - ide-typescript

  # Linters / Formatters
  # - linter-eslint
  # - linter-tslint
  # - prettier-atom

  # Themes
  - file-icons

  - teletype

vscode_extensions:
  # General
  - { name: "Debugger for Chrome", id: "msjsdiag.debugger-for-chrome" }
  - { name: "EditorConfig for VS Code", id: "EditorConfig.EditorConfig" }
  # - Tyriar.sort-lines
  
  # Linter / Formatters
  # - { name: "Eslint", id: "dbaeumer.vscode-eslint" }
  - { name: "TS Lint", id: "eg2.tslint" }
  - { name: "Prettier", id: "esbenp.prettier-vscode" }

  # Others
  # - { name: "Docker", id: "PeterJausovec.vscode-docker" }
  # - { name: "Go", id: "lukehoban.Go" }
  - { name: "Settings Sync", id: "Shan.code-settings-sync" }
  - { name: "TODO Highlight", id: "wayou.vscode-todo-highlight" }
  
  # Theme
  - { name: "vscode-icons", id: "robertohuertasm.vscode-icons" }

# Git  
git_push_default: "simple"
git_user_name: "Gustavo Perdomo"
git_user_email: "gperdomor@gmail.com"

# Node  
node_pkgs_list:
  - name: "@angular/cli"
  - name: create-react-app
  - name: create-react-native-app
  - name: react-native-cli