---
- hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - block:
        - name: Verify Ansible version.
          assert:
            that: "ansible_version.full is version_compare('2.10', '>=')"
            msg: "You must update Ansible to at least 2.10 to use this version of macOS-ansible."

        - name: Verify target system is running macOS.
          assert:
            that: "ansible_distribution == 'MacOSX'"
            msg: "The target system is not running macOS."

        - name: Verify macOS version.
          assert:
            that: "ansible_distribution_version is version_compare('10.14', '>=')"
            msg: "The target system must be running macOS 10.14 or higher to use this version of macOS-setup."

        - name: Include configuration
          include_vars: "{{ item }}"
          with_first_found:
            - files:
                - config.yml
                - default.config.yml
              skip: true
      tags: ["always"]

  roles:
    - role: homebrew
      tags: [homebrew]
    - role: shell
      tags: [shell]
    - role: nvm
      tags: [nvm]
    - role: mas
      when: mas_apps|count > 0
      tags: [mas]
    - role: settings
      tags: [settings]
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: [dotfiles]
