---
- name: macOS Setup
  hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

    - block:
      - name: Verify Ansible version.
        assert:
          that: "ansible_version.full is version_compare('2.4', '>=')"
          msg: "You must update Ansible to at least 2.4 to use this version of Macsible."

      - name: Verify target system is running macOS.
        assert:
          that: "ansible_distribution == 'MacOSX'"
          msg: "The target system is not running macOS."

      - name: Verify macOS version.
        assert:
          that: "ansible_distribution_version is version_compare('10.10', '>=')"
          msg: "The target system must be running macOS 10.10 or higher to use this version of Macsible."
      tags: ["always"]

  roles:
    - role: geerlingguy.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ["mas"]

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ["terminal"]

    - include_tasks: tasks/osx.yml
      when: configure_osx
      tags: ["osx"]

    - include_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]

    - include_tasks: tasks/ssh.yml
      when: configure_ssh
      tags: ["ssh"]

    - include_tasks: tasks/projects.yml
      when: configure_projects and configure_ssh
      tags: ["projects"]

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
