---
- name: Configure macOS
  hosts: localhost

  vars_files:
    - config.yml

  pre_tasks:
    - name: "Verifying playbook requirements"
      tags: ["always"]
      block:
        - name: Verify Ansible version.
          assert:
            that: "ansible_version.full is version_compare('2.11.0', '>=')"
            msg: "You must update Ansible to at least 2.11.0 to use this version of macOS-ansible."

        - name: Verify target system is running macOS.
          assert:
            that: "ansible_distribution == 'MacOSX'"
            msg: "The target system is not running macOS."

        - name: Verify macOS version.
          assert:
            that: "ansible_distribution_version is version_compare('10.15', '>=')"
            msg: "The target system must be running macOS 10.15 (Catalina) or higher to use this version of macOS-ansible."

  roles:
    - role: homebrew
      tags: [homebrew]
    - role: shell
      tags: [shell]
    - role: node
      tags: [node]
    - role: mas
      when: mas_apps|count > 0
      tags: [mas]
    - role: projects
      when: projects|count > 0
      tags: [projects]
    - role: settings
      tags: [settings]
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: [dotfiles]
