---

- name: macOS-ansible
  hosts: all
  connection: local

  vars_files:
    - config.yml
    # - config/config.yml
    # - config/config.local.yml

  pre_tasks:
    - block:
      - name: Verify Ansible version.
        assert:
          that: "ansible_version.full | version_compare('2.4', '>=')"
          msg: "You must update Ansible to at least 2.4 to use this version of Macsible."

      - name: Verify target system is running macOS.
        assert:
          that: "ansible_distribution == 'MacOSX'"
          msg: "The target system is not running macOS."

      - name: Verify macOS version.
        assert:
          that: "ansible_distribution_version | version_compare('10.10', '>=')"
          msg: "The target system must be running macOS 10.10 or higher to use this version of Macsible."

      tags: always

- import_playbook: mac-custom.yml
