---
# Cask.
- name: Ensure blacklisted cask applications are not installed.
  homebrew_cask:
    name: "{{ item }}"
    state: "absent"
  loop: "{{ homebrew_cask_uninstalled_apps }}"

- name: Install configured cask applications.
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
    accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
  loop: "{{ homebrew_cask_apps }}"

# Brew.
- name: Ensure blacklisted homebrew packages are not installed.
  homebrew:
    name: "{{ item }}"
    state: "absent"
  loop: "{{ homebrew_uninstalled_packages }}"

- name: Ensure configured homebrew packages are installed.
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop: "{{ homebrew_installed_packages }}"
