---
- name: Ensure NVM is installed.
  homebrew:
    name: nvm
    state: present

- name: Install default node version.
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ node_default_version }}
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_default_version }}"

- name: Make Node {{ node_default_version }} as default.
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm alias default {{ node_default_version }}
  changed_when: false

- name: Install global NPM packages.
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: yes
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ npm_packages }}"
