---
- name: Ensure ~/.ssh exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0700

# - name: Ensure ~/.ssh/known_hosts exists
#   file:
#     path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
#     state: touch
#     mode: 0644
#   changed_when: false
#
# - name: Add hosts to known_hosts
#   known_hosts:
#     path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
#     name: "{{ item.host }}"
#     key: "{{ item.key }}"
#   with_items: "{{ ssh_known_hosts }}"

- name: Generate ssh keys
  user:
    name: "{{ansible_user}}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_passphrase: "{{item.passphrase}}"
    ssh_key_file: ".ssh/{{item.name}}"
  items: "{{ssh_keys}}"

- name: Add {{item.host}} ssh config into config file
  blockinfile:
    path: ~/.ssh/config
    create: yes
    backup: yes
    marker: "# {mark} {{ item.name }}"
    content: |
      Host {{item.host}}
       AddKeysToAgent yes
       UseKeychain yes
       IdentityFile ~/.ssh/{{item.name}}
  items: "{{ssh_keys}}"

- name: Enable ssh agent
  shell: eval `ssh-agent -s`

- name: Add ssh private keys to ssh agent
  expect:
    command: "ssh-add -K /Users/{{ansible_user}}/.ssh/{{item.name}}"
    responses:
      (?i)Enter passphrase: "{{item.passphrase}}"
  items: "{{ssh_keys}}"
