---
- name: Installing zsh
  homebrew:
    name: ['zsh', 'zsh-completions']
    state: present

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh
  become: true
