---

- name: Ensure ~/.ssh exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0700

- name: Ensure ~/.ssh/known_hosts exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    state: touch
    mode: 0644
  changed_when: false

- name: Add hosts to known_hosts
  known_hosts:
    path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    name: "{{ item.host }}"
    key: "{{ item.key }}"
  with_items: "{{ ssh_known_hosts }}"
