---

- name: Install Transmission
  homebrew_cask: name=transmission state=present

- name: Ensure location for incomplete downloads exists
  file:
    path: "{{ ansible_env.HOME }}/Downloads/Torrents/Incomplete"
    state: directory
    follow: yes

- name: "{{ item.name }}"
  osx_defaults:
    domain: org.m0k.transmission
    key: "{{ item.key }}"
    type: bool
    value: "{{ item.value }}"
  with_items:
    - { name: "Keep incomplete downloads", key: "UseIncompleteDownloadFolder", value: "true" }
    - { name: "Don't prompt for confirmation before downloading (1/2)", key: "DownloadAsk", value: "false" }
    - { name: "Don't prompt for confirmation before downloading (2/2)", key: "MagnetOpenAsk", value: "false" }
    - { name: "Trash original torrent files", key: "DeleteOriginalTorrent", value: "true" }
    - { name: "Hide the donate message", key: "WarningDonate", value: "false" }
    - { name: "Hide the legal disclaimer", key: "WarningLegal", value: "false" }
    - { name: "Randomize port on launch", key: "RandomPort", value: "true" }
  notify: killall Transmission

- name: "{{ item.name }}"
  osx_defaults:
    domain: org.m0k.transmission
    key: "{{ item.key }}"
    type: string
    value: "{{ item.value }}"
  with_items:
    - { name: "Set path for incomplete downloads", key: "IncompleteDownloadFolder", value: "${HOME}/Downloads/Torrents/Incomplete" }
    - { name: "Set path for downloads", key: "NSNavLastRootDirectory", value: "${HOME}/Downloads/Torrents" }
  notify: killall Transmission
