version: 2

jobs:
  macos:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: bash init.sh
      # Debug info
      - run: python --version
      - run: ansible --version
      # Run
      - run: ansible-playbook playbook.yml --syntax-check
      - run: ansible-playbook playbook.yml --skip-tags "skip_ci,mas_app,xcode"

workflows:
  version: 2
  tests:
    jobs:
      - macos
