version: 2

jobs:
  macos:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Install pip.
          command: easy_install pip
      - run:
          name: Install Ansible.
          command: pip install ansible
      - run:
          name: Install pexpect.
          command: pip install pexpect -U --quiet
      - run:
          name: Install dependencies
          command: ansible-galaxy install -r requirements.yml
      - run:
          name: Checking the role/playbook's syntax
          command: ansible-playbook main.yml --syntax-check
      - run:
          name: Copy test config.yml into place.
          command: cp tests/config.yml config.yml
      - run:
          name: Run playbook
          command: ansible-playbook main.yml -i inventory --skip-tags "mas"
      # Test the playbook's idempotence.
      # - run: idempotence=$(mktemp)
      # - run: ansible-playbook --extra-vars '{"configure_terminal":"false"}' main.yml -i inventory --skip-tags "mas" | tee -a ${idempotence}
      # - run: >
      #     tail ${idempotence}
      #     | grep -q 'changed=0.*failed=0'
      #     && (echo 'Idempotence test: pass' && exit 0)
      #     || (echo 'Idempotence test: fail' && exit 1)

workflows:
  version: 2
  tests:
    jobs:
      - macos
