version: 2

jobs:
  macos:
    macos:
      xcode: '10.2.1'
    steps:
      # - restore_cache:
      #     keys:
      #       - packages-{{ .Branch }}-{{ .Revision }}
      #       - packages-{{ .Branch }}-
      #       - packages-
      - checkout
      - run:
          name: Install dependencies.
          command: bash scripts/install_deps.sh
      # - run:
      #     name: Install pexpect.
      #     command: pip install pexpect -U --quiet
      - run:
          name: Install dependencies
          command: ansible-galaxy install -r custom/requirements.yml --force
      - run:
          name: Create config.local file
          command: touch custom/config.local.yml
      - run:
          name: Checking the role/playbook's syntax
          command: ansible-playbook custom/mac.yml --syntax-check
      # - run:
      #     name: Copy test config.yml into place.
      #     command: cp tests/config.yml config.yml
      - run:
          name: Run playbook
          command: ansible-playbook custom/mac.yml --skip-tags "mas,no_ci"
      # Test the playbook's idempotence.
      # - run: idempotence=$(mktemp)
      # - run: ansible-playbook --extra-vars '{"configure_terminal":"false"}' main.yml --skip-tags "mas" | tee -a ${idempotence}
      # - run: >
      #     tail ${idempotence}
      #     | grep -q 'changed=0.*failed=0'
      #     && (echo 'Idempotence test: pass' && exit 0)
      #     || (echo 'Idempotence test: fail' && exit 1)
      # - save_cache:
      #     key: packages-{{ .Branch }}-{{ .Revision }}
      #     paths:
      #       - '$HOME/Library/Caches/pip'
      #       - '$HOME/Library/Caches/Homebrew'

workflows:
  version: 2
  tests:
    jobs:
      - macos
