---

- name: Show the main window when launching Activity Monitor
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true
  notify:
    - killall

- name: Show all processes in Activity Monitor
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 0
  notify:
    - killall

- name: Sort Activity Monitor results by CPU usage (1)
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortColumn
    type: string
    value: "CPUUsage"
  notify:
    - killall

- name: Sort Activity Monitor results by CPU usage (2)
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortDirection
    type: int
    value: 0
  notify:
    - killall
