---

- name: Set the icon size of Dock items
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 42
  notify:
    - killall Dock

# - name: Set Dock orientation
#   osx_defaults:
#     domain: com.apple.dock
#     key: orientation
#     type: string
#     value: "bottom"
#   notify:
#     - killall Dock

# - name: Automatically hide and show the Dock
#   osx_defaults:
#     domain: com.apple.dock
#     key: autohide
#     type: bool
#     value: true
#   notify:
#     - killall Dock
