---
- name: Custom - Last
  hosts: localhost

  vars_files:
    - config.yml
    - config.local.yml

  roles:
    - { cask_app_name: "font-cascadia", tags: ["font", "font-cascadia"], role: danbohea.cask-app }

  post_tasks:
    - debug:
        msg: "Some changes may not take effect until you've restarted your Mac."
      tags: always
