---

# This is a re-usable role for a basic package install via Homebrew.

- name: Install {{ brew_pkg_name }}
  homebrew:
    name: "{{ brew_pkg_name }}"
    install_options: "{{ brew_pkg_install_options }}"
    state: present
  notify: brew cleanup

- name: Run homebrew postinstall command
  command: "{{ brew_pkg_post_install }}"
  when: brew_pkg_post_install is defined