---

- name: Install Sketch & supporting tools.
  homebrew_cask: name="{{ item }}" state=present
  with_items: "{{ sketch_apps }}"
  notify: brew cask cleanup

- name: Ensure Sketch plugins directory exists.
  file:
    path: "{{ sketch_plugins_dir }}"
    state: directory

- name: Determine destination directory from Git repo path.
  shell: basename {{ item }} | cut -f 1 -d '.'
  with_items: "{{ sketch_plugin_repos }}"
  register: sketch_plugin_dests
  changed_when: false

- name: Clone plugins to Sketch plugins directory.
  git:
    repo: "{{ item.0 }}"
    dest: "{{ sketch_plugins_dir }}/{{ item.1.stdout }}"
    depth: 1
    version: master
  with_together:
    - "{{ sketch_plugin_repos }}"
    - "{{ sketch_plugin_dests.results }}"
