---

- name: Install duti
  homebrew: name=duti
  notify: brew cleanup

# NOTE: ~/.duti should be provided by the dotfiles role

- name: Check that ~/.duti preferences file exists
  file:
    path: ~/.duti
    state: file
    follow: yes

# TODO: Make idempotent
- name: Run duti with preferences file
  shell: duti ~/.duti
