---

- name: Install Tower
  homebrew_cask: name=tower state=present
  notify: brew cleanup

# Use Homebrew git binary
- name: Set default Git binary
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsGitBinary
    type: string
    value: /usr/local/bin/git
  notify: killall Tower

- name: Set default directory for cloned projects
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsDefaultCloningDirectory
    type: string
    value: ${HOME}/Projects
  notify: killall Tower

# TODO: Check if Kaleidoscope is installed first.
- name: Set diff tool
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsDiffToolIdentifier
    type: string
    value: kaleidoscope
  notify: killall Tower
