---

- name: Install Tower
  homebrew_cask: name=tower state=present

# Use Homebrew git binary
- name: Set default Git binary
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsGitBinary
    type: string
    value: /usr/local/bin/git
  notify: killall Tower

- name: Ensure ~/Developer directory exists
  file:
    path: ${HOME}/Developer
    state: directory
    follow: yes

- name: Set default directory for cloned projects
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsDefaultCloningDirectory
    type: string
    value: ${HOME}/Developer
  notify: killall Tower

- name: Check if Kaleidoscope is installed
  stat: path=/Applications/Kaleidoscope.app
  register: kaleidoscope_check
  tags: ['homebrew']

- name: Set diff tool
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsDiffToolIdentifier
    type: string
    value: kaleidoscope
  when: 'kaleidoscope_check.stat.exists == True'
  notify: killall Tower

- name: Check if P4Merge is installed
  stat: path=/Applications/p4merge.app
  register: p4merge_check

- name: Set merge tool
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsMergeToolIdentifier
    type: string
    value: p4merge
  when: 'p4merge_check.stat.exists == True'
  notify: killall Tower