---

- name: Install Tower
  homebrew_cask: name=tower state=present
  notify: brew cask cleanup

- name: Use Homebrew Git binary
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsGitBinary
    type: string
    value: /usr/local/bin/git
  notify: killall Tower

- name: Set default directory for cloned projects
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsDefaultCloningDirectory
    type: string
    value: ${HOME}/Developer
  notify: killall Tower

# TODO: Check if araxismerge is installed first.
- name: Set default diff tool
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsDiffToolIdentifier
    type: string
    value: araxismerge
  notify: killall Tower

# TODO: Check if p4merge is installed first.
- name: Set default merge tool
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsMergeToolIdentifier
    type: string
    value: p4merge
  notify: killall Tower
