---

- name: Install Tower
  homebrew_cask: name=tower state=present
  notify: brew cask cleanup

- name: Use Homebrew Git binary
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsGitBinary
    type: string
    value: /usr/local/bin/git
  notify: killall Tower

- name: Set default directory for cloned projects
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsDefaultCloningDirectory
    type: string
    value: ${HOME}/Developer
  notify: killall Tower

- name: Check if Kaleidoscope is installed
  stat: path=/Applications/Kaleidoscope.app
  register: kaleidoscope_check

- name: Set diff tool
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsDiffToolIdentifier
    type: string
    value: kaleidoscope
  notify: killall Tower
  when: kaleidoscope_check.stat.exists == True

- name: Check if P4Merge is installed
  stat: path=/Applications/p4merge.app
  register: p4merge_check

- name: Set merge tool
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsMergeToolIdentifier
    type: string
    value: p4merge
  notify: killall Tower
  when: p4merge_check.stat.exists == True

