---
- name: "Running Homebrew Tasks"
  block:
    - name: Install Homebrew Formulas
      community.general.homebrew:
        name: "{{ item }}"
        state: present
        update_homebrew: true
      loop: "{{ brew_packages }}"

    - name: Install Homebrew Casks
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
        update_homebrew: true
      loop: "{{ brew_casks }}"
