---
- name: Ensure ~/Developer directory exists
  file:
    path: ~/Developer
    state: directory
    follow: yes

# OSS projects

- name: Clone OSS project repos
  git:
    repo: "{{ item.repo }}"
    dest: ~/Developer/oss/{{ item.dest }}
    accept_hostkey: yes
    version: master
  with_items: "{{ projects_oss }}"
  changed_when: false

- name: Set git remote URL to SSH on oss projects
  shell: git remote set-url origin {{ item.repo_ssh }}
  with_items: "{{ projects_oss }}"
  args:
    chdir: "~/Developer/oss/{{ item.dest }}"
    warn: false
  changed_when: false

# Internal projects

- name: Clone internal project repos
  git:
    repo: "{{ item.repo }}"
    dest: ~/Developer/internal/{{ item.dest }}
    accept_hostkey: yes
    version: master
  with_items: "{{ projects_internal }}"
  changed_when: false

- name: Set git remote URL to SSH on internal projects
  shell: git remote set-url origin {{ item.repo_ssh }}
  with_items: "{{ projects_internal }}"
  args:
    chdir: "~/Developer/internal/{{ item.dest }}"
    warn: false
  changed_when: false

# Client projects

- name: Clone client project repos
  git:
    repo: "{{ item.repo }}"
    dest: ~/Developer/client/{{ item.dest }}
    accept_hostkey: yes
    version: master
  with_items: "{{ projects_client }}"
  changed_when: false

- name: Set git remote URL to SSH  on client projects
  shell: git remote set-url origin {{ item.repo_ssh }}
  with_items: "{{ projects_client }}"
  args:
    chdir: "~/Developer/client/{{ item.dest }}"
    warn: false
  changed_when: false
