---
- name: Ensure ~/.ssh existsssss
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"
  when: configure_ssh

- name: Generate ssh keys
  openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/{{item.name}}"
    type: "{{ item.type | default('ed25519')}}"
    comment: "{{ item.comment | default(omit)}}"
  with_items: "{{ ssh_keys }}"
  when: configure_ssh

- name: Configure the users ssh config file
  template:
    src: "config.j2"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: "0600"
  when: configure_ssh

- name: Enable ssh agent
  shell: eval `ssh-agent -s`
  changed_when: false
  when: configure_ssh

- name: Add ssh private keys to ssh agent
  shell: "ssh-add -K {{ ansible_env.HOME }}/.ssh/{{item.name}}"
  with_items: "{{ ssh_keys }}"
  changed_when: false
  when: configure_ssh
