---
configure_dotfiles: yes
configure_terminal: yes
configure_osx: yes
configure_ssh: yes
configure_projects: yes

# dotfiles
# --------------------------------------------------------------------------
dotfiles_repo: https://gitlab.com/gperdomor/dotfiles.git
dotfiles_repo_ssh: git@gitlab.com:gperdomor/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .zshrc

# Homebrew
# --------------------------------------------------------------------------
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - vapor/tap
  - kylef/formulae
  - adoptopenjdk/openjdk

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # - cowsay
  - curl
  - diff-so-fancy
  # - docker-machine
  # - docker-machine-driver-hyperkit
  # - docker-machine-parallels
  - git
  # - gitlab-runner
  # - go
  # - gpg
  # - heroku
  - httpie
  # - hub
  # - kubernetes-cli
  - nmap
  - node
  # - nvm
  - openssl
  - pgcli
  # - postgresql
  # - python
  # - rbenv
  # - ruby-build
  # - sqlite
  # - ssh-copy-id
  # - swiftenv
  # - swiftformat
  # - swiftlint # Require Xcode
  - tree
  - vapor
  # - watchman
  - wget
  # - yarn
  - zsh
  - zsh-completions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-studio
  - angular-console
  # - araxis-merge
  # - atom
  # - cleanmymac
  - discord
  - docker
  - dockstation
  - dropbox
  - duet
  - firefox
  # - gemini
  - google-chrome
  - gpg-suite
  - iina
  - insomnia
  - kaleidoscope
  - keepingyouawake
  - kitematic
  # - knuff
  - minikube
  - navicat-premium
  - ngrok
  - opera
  - p4v
  # - parallels
  # - paw
  - pgadmin4
  - postman
  - skype
  - tableplus
  # - the-unarchiver
  - tower
  - transmission
  # - vagrant
  - visual-studio-code
  # - vlc
  - vmware-fusion
  # - webstorm
  # - xscope

# Mac App Store
# --------------------------------------------------------------------------
# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { name: "1Password 7", id: 1333542190 }
  # - { name: "Affinity Designer", id: 824171161 }
  # - { name: "Affinity Photo" id: 824183456 }
  - { name: "Agenda", id: 1287445660 }
  - { name: "Keynote", id: 409183694 }
  - { name: "Magnet", id: 441258766 }
  - { name: "Money", id: 1185488696 }
  - { name: "Numbers", id: 409203825 }
  - { name: "Pages", id: 409201541 }
  # # - { name: "Pixelmator Pro", id: 1289583905 }
  # # - { name: "Pixelmator", id: 407963104 }
  - { name: "Reeder", id: 880001334 }
  - { name: "Slack", id: 803453959 }
  - { name: "Spark", id: 1176895641 }
  - { name: "The Unarchiver", id: 425424353 }
  - { name: "Xcode", id: 497799835 }

mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.

# Atom Packages
# --------------------------------------------------------------------------
atom_packages:
  - editorconfig
  - file-icons
  - highlight-selected
  - pigments
  - prettier-atom
  - sort-lines
  - teletype

# VS Code Packages
# --------------------------------------------------------------------------
vscode_packages:
  # - { name: "Angular Console", id: "nrwl.angular-console" }
  # - { name: "Angular Languiase Service", id: "Angular.ng-template" }
  # - { name: "Copilot", id: "Metatype.copilot-vscode" }
  # - { name: "Debugger for Chrome", id: "msjsdiag.debugger-for-chrome" }
  # - { name: "Docker", id: "PeterJausovec.vscode-docker" }
  # - { name: "Dot Env", id: "mikestead.dotenv" }
  # - { name: "EditorConfig for VS Code", id: "EditorConfig.EditorConfig" }
  # - { name: "Git Lens", id: "eamodio.gitlens" }
  # - { name: "Jest", id: "Orta.vscode-jest" }
  # - { name: "Live Share", id: "ms-vsliveshare.vsliveshare" }
  # - { name: "Markdown All in One", id: "yzhang.markdown-all-in-one" }
  # - { name: "One Dark Pro", id: "yzhzhuangtongfa.Material-theme" }
  # - { name: "Prettier", id: "esbenp.prettier-vscode" }
  - { name: "Settings Sync", id: "shan.code-settings-sync" }
  # - { name: "Sort Lines", id: "Tyriar.sort-lines" }
  # - { name: "Sort Typescript Imports", id: "miclo.sort-typescript-imports" }
  # - { name: "TODO Tree", id: "Gruntfuggly.todo-tree" }
  # - { name: "TS Lint", id: "ms-vscode.vscode-typescript-tslint-plugin" }
  # - { name: "vscode-icons", id: "vscode-icons-team.vscode-icons" }

# Composer Packages
# --------------------------------------------------------------------------
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A

# Ruby Gems
# --------------------------------------------------------------------------
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A

# Node Packages
# --------------------------------------------------------------------------
npm_packages:
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
  - name: "@angular/cli"
  - name: "@nestjs/cli"
  - name: "@nrwl/schematics"
  - name: create-react-app
  - name: expo-cli
  - name: json-server
  - name: nodemon
  - name: npm
    version: 6.8.0
  - name: npm-check
  - name: oclif
  - name: prettier
  - name: react-native-cli
  - name: serve
  - name: typescript

# Python Packages
# --------------------------------------------------------------------------
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Projects
# --------------------------------------------------------------------------
projects_oss:
  # - dest: "oss-repo"
  #   repo_https: "https://{{ githubuser | urlencode }}:{{ githubpassword }}@github.com/private-repo.git"
  #   repo_ssh: "git@github.com:githubuser/private-repo.git"
  - { dest: "macOs-ansible", repo: "https://github.com/gperdomor/macOs-ansible.git" }
projects_internal:
  # - dest: "private-repo"
  #   repo_https: "https://{{ githubuser | urlencode }}:{{ githubpassword }}@github.com/private-repo.git"
  #   repo_ssh: "git@github.com:githubuser/private-repo.git"
  - { dest: "macOs-ansible", repo: "https://github.com/gperdomor/macOs-ansible.git" }
projects_client:
  # - dest: "client-repo"
  #   repo_https: "https://{{ githubuser | urlencode }}:{{ githubpassword }}@github.com/private-repo.git"
  #   repo_ssh: "git@github.com:githubuser/private-repo.git"
  - { dest: "macOs-ansible", repo: "https://github.com/gperdomor/macOs-ansible.git" }

# Glob pattern to ansible task files to run after all other tasks are finished.
# post_provision_tasks:
#   - tasks/posts-provision/chrome.yml
#   - tasks/posts-provision/curl.yml
#   - tasks/posts-provision/dotfiles.yml
#   - tasks/posts-provision/tower.yml
#   - tasks/posts-provision/transmission.yml
