---
- name: Running Node Tasks using Fast Node Manager (FNM) in macOS
  import_tasks: macos.yml
  when: ansible_distribution == "MacOSX"

- name: Running Node Tasks using Fast Node Manager (FNM) in macOS
  import_tasks: install-packages.yml
