---

# Override default role variables here.

# atom
# ------------------------------------------------------------------------------

atom_packages:
  - afterglow-monokai-syntax
  - atom-beautify
  - atom-ide-ui
  - atom-json-color
  - atom-jinja2
  - atom-terminal-tab
  - atom-twig
  - atom-wrap-in-tag
  - autoclose-html
  - autocomplete-paths
  - autocomplete-plus
  - docblockr
  - double-tag
  - editorconfig
  - emmet
  - file-icons
  - fix-indent-on-paste
  - git-time-machine
  - highlight-line
  - highlight-selected
  - ide-css
  - ide-html
  - ide-json
  - ide-vue
  - ide-yaml
  - isotope-ui
  - language-ansible
  - language-docker
  - language-ignore
  - language-nunjucks
  - language-patch
  - language-vue
  - less-than-slash
  - linter-ansible-syntax
  - linter-eslint
  - linter-htmlhint
  - linter-jsonlint
  - local-history
  - markdown-writer
  - minimap
  - minimap-linter
  - open-recent
  - open-terminal-here
  - pigments
  - project-manager
  - sort-lines
  - svg-preview
  - tabs-to-spaces
  - todo-show
  - toggle-quotes
  - travis-ci-status
  - tree-view-autoresize
  - tree-view-copy-relative-path

# dock items
# ------------------------------------------------------------------------------

# Filenames must include .app extension.
macos_dock_apps:
  - /Applications/Path Finder.app
  - /Applications/Slack.app
  - /Applications/Firefox.app
  - /Applications/Inkdrop.app
  - /Applications/Evernote.app
  - /Applications/Skitch.app
  - /Applications/Calendar.app
  - /Applications/Atom.app
  - /Applications/PhpStorm.app
  - /Applications/Todoist.app
  - /Applications/System Preferences.app
  - /Applications/xScope.app
  - /Applications/Tower.app
  - /Applications/iTerm.app

# sketch
# ------------------------------------------------------------------------------

sketch_plugin_repos:
  - https://github.com/bomberstudios/sketch-commands.git
  - https://github.com/ddwht/sketch-dynamic-button.git
  - https://github.com/getflourish/Sketch-Style-Inventory.git
  - https://github.com/marcosvidal/Sketch-Notebook
  - https://github.com/ScottSavarie/Clipboard-Fill.git
  - https://github.com/timuric/Content-generator-sketch-plugin.git
  - https://github.com/tylergaw/day-player.git
