---
- name: Custom - First
  hosts: localhost

  vars_files:
    - config.yml
    - config.local.yml

  roles:
    - { role: macos, tags: "macos" }
    - { role: ssh, tags: ["ssh","no_ci"] }
    - { role: terminal, tags: ["terminal"] }
    - { role: quick-look-plugins, tags: ["quick_look_plugins"] }
    - { role: vscode, tags: ["vscode"] }
    # - { role: danbohea.atom, tags: ["atom"] }

  # TODO CHECK THIS
  tasks:
    - name: "Installing Cask App {{ item }}"
      homebrew_cask:
        state: present
        name:
          - dropbox
          - google-chrome
          - gpg-suite