---

- name: Ensure ~/Developer directory exists
  file:
    path: ~/Developer
    state: directory
    follow: yes

- name: Clone project repos
  git:
    repo: "{{ item.repo }}"
    dest: ~/Developer/{{ item.dest }}
    accept_hostkey: yes
    version: master
  with_items: "{{ projects }}"
