---

- name: Ensure ~/Developer directory exists
  file:
    path: ~/Developer
    state: directory
    follow: yes

- name: Clone projects repos
  git:
    repo: "{{ item.repo_https }}"
    dest: ~/Developer/{{ item.dest }}
    accept_hostkey: yes
    version: master
  with_items: "{{ projects }}"

- name: Set git remote URL to SSH
  shell: git remote set-url origin {{ item.repo_ssh }}
  with_items: "{{ projects }}"
  args:
    chdir: "~/Developer/{{ item.dest }}"
    warn: false