---

- name: Install {{ mas_app_name }} - {{ mas_app_id }}.
  shell: mas list | grep "{{ mas_app_id }}" || mas install "{{ mas_app_id }}"
  register: result
  changed_when: result.stdout.find('Installed') != -1
  when: mas_email is defined and mas_password is defined and mas_email != '' and mas_password != '' and mas_account_result.rc != 1
  tags:
    - mas_app
    - no_ci

- name: Upgrade {{ mas_app_name }} - {{ mas_app_id }}.
  shell: mas list | grep "{{ mas_app_id }}" || mas upgrade "{{ mas_app_id }}"
  register: result
  changed_when: result.stdout.find('Installed') != -1
  when: mas_email is defined and mas_password is defined and mas_email != '' and mas_password != '' and mas_account_result.rc != 1
  tags:
    - mas_app
    - no_ci
