---

- name: Install Docker
  homebrew_cask: name=docker state=present
  notify: brew cask cleanup

- name: Install Docker completions
  file:
    src: "/Applications/Docker.app/Contents/Resources/etc/{{ item }}.zsh-completion"
    dest: "/usr/local/share/zsh/site-functions/_{{ item }}"
    state: link
  with_items:
    - "docker"
    - "docker-machine"
    - "docker-compose"