---

- name: Show the main window when launching Activity Monitor
  command: defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

- name: Visualize CPU usage in the Activity Monitor Dock icon
  command: defaults write com.apple.ActivityMonitor IconType -int 5

- name: Show all processes in Activity Monitor
  command: defaults write com.apple.ActivityMonitor ShowCategory -int 0

- name: Sort Activity Monitor results by CPU usage (1/2)
  command: defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"

- name: Sort Activity Monitor results by CPU usage (2/2)
  command: defaults write com.apple.ActivityMonitor SortDirection -int 0
