---

- name: Set Home as the default location for new Finder windows
  osx_defaults:
    domain: com.apple.finder
    key: "{{ item.key }}"
    type: string
    value: "{{ item.value }}"
  with_items:
    - key: NewWindowTarget
      value: PfHm
    - key: NewWindowTargetPath
      value: "file://${HOME}/"
  changed_when: false

- name: "{{ item.name }}"
  osx_defaults:
    domain: com.apple.finder
    key: "{{ item.key }}"
    type: bool
    value: "{{ item.value | default(true) }}"
  with_items:
    # - name: Disable the warning before emptying the Trash
    #   key: WarnOnEmptyTrash
    #   value: false
    # - name: Disable the warning when changing a file extension
    #   key: FXEnableExtensionChangeWarning
    #   value: false
    - name: Empty Trash securely by default
      key: EmptyTrashSecurely
    - name: Show external hard drives on the desktop
      key: ShowExternalHardDrivesOnDesktop
    # - name: Show internal hard drives on the desktop
    #   key: ShowHardDrivesOnDesktop
    - name: Show mounted servers on the desktop
      key: ShowMountedServersOnDesktop
    - name: Show removable media on the desktop
      key: ShowRemovableMediaOnDesktop
    # - name: Show hidden files by default
    #   key: AppleShowAllFiles
    - name: Show status bar
      key: ShowStatusBar
    # - name: Show path bar
    #   key: ShowPathbar
    - name: Allow text selection in Quick Look
      key: QLEnableTextSelection
    # - name: Display full POSIX path as Finder window title
    #   key: _FXShowPosixPathInTitle
    # - name: Avoid creating .DS_Store files on network volumes
    #   key: DSDontWriteNetworkStores

- name: When performing a search, search the current folder by default
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf

- name: "{{ item.name }}"
  osx_defaults:
    domain: NSGlobalDomain
    key: "{{ item.key }}"
    type: bool
    value: true
  with_items:
    - name: Show all filename extensions
      key: AppleShowAllExtensions
    - name: Enable spring loading for directories
      key: com.apple.springing.enabled

- name: Remove the spring loading delay for directories
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.delay
    type: float
    value: 0.1

- name: Avoid creating .DS_Store files on network volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: Automatically open a new Finder window when a volume is mounted
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: bool
    value: true
  with_items:
    - domain: com.apple.frameworks.diskimages
      key: auto-open-ro-root
    - domain: com.apple.frameworks.diskimages
      key: auto-open-rw-root
    - domain: com.apple.finder
      key: OpenWindowForNewRemovableDisk


# Four-letter codes for the other view modes: `icnv`, `Nlsv`, `clmv`, `Flwv`
# - name: Use column view in all Finder windows by default
#   osx_defaults:
#     domain: com.apple.finder
#     key: FXPreferredViewStyle
#     type: string
#     value: clmv

- name: Enable snap-to-grid for icons on the desktop and in other icon views
  command: /usr/libexec/PlistBuddy -c "Set :{{ item }} grid" ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - DesktopViewSettings:IconViewSettings:arrangeBy
    - StandardViewSettings:IconViewSettings:arrangeBy
  changed_when: false

- name: Set the size of icons on the desktop and in other icon views
  command: /usr/libexec/PlistBuddy -c "Set :{{ item }} 64" ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - DesktopViewSettings:IconViewSettings:iconSize
    - StandardViewSettings:IconViewSettings:iconSize
  changed_when: false

# - name: Show the ~/Library folder
#   command: chflags nohidden ~/Library
#   changed_when: false

- name: 'Expand the following File Info panes: "General", "Open with", "Sharing & Permissions"'
  command: >
    defaults write com.apple.finder FXInfoPanesExpanded -dict \
      General -bool true \
      OpenWith -bool true \
      Preview -bool false \
      Privileges -bool true
  changed_when: false
