---

# - name: Disable send and reply animations in Mail.app
#   command: defaults write com.apple.mail {{ item }} -bool true
#   with_items:
#     - DisableReplyAnimations
#     - DisableSendAnimations

# - name: Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
#   command: defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

# - name: Add the keyboard shortcut ⌘ + Enter to send an email in Mail.app
#   command: defaults write com.apple.mail NSUserKeyEquivalents -dict-add "Send" -string "@\\U21a9"

- name: Display emails in threaded mode
  command: defaults write com.apple.mail DraftsViewerAttributes -dict-add "DisplayInThreadedMode" -string "yes"
  # defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortedDescending" -string "yes"
  # defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortOrder" -string "received-date"

# - name: Disable inline attachments (just show the icons)
#   command: defaults write com.apple.mail DisableInlineAttachmentViewing -bool true

# - name: Disable spell checking
#   command: defaults write com.apple.mail SpellCheckingBehavior -string "NoSpellCheckingEnabled"
