---
- name: Use Homebrew Git binary
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsGitBinary
    type: string
    value: /usr/local/bin/git
  when: "'git' in homebrew_installed_packages"

- name: Set default directory for cloned projects
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsDefaultCloningDirectory
    type: string
    value: ${HOME}/Developer

- name: Set default diff tool
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsDiffToolIdentifier
    type: string
    value: kaleidoscope
  when: "'kaleidoscope' in homebrew_cask_apps"

- name: Set default merge tool
  osx_defaults:
    domain: com.fournova.Tower2
    key: GTUserDefaultsMergeToolIdentifier
    type: string
    value: p4merge
  when: "'p4merge' in homebrew_cask_apps"
