---
projects_oss:
  - dest: "macOS-ansible"
    repo: "https://github.com/gperdomor/macOS-ansible.git"
    repo_ssh: "git@github.com:gperdomor/macOS-ansible.git"

projects_internal:
  - dest: "macOS-ansible"
    repo: "https://github.com/gperdomor/macOS-ansible.git"
    repo_ssh: "git@github.com:gperdomor/macOS-ansible.git"

projects_client:
  - dest: "macOS-ansible"
    repo: "https://github.com/gperdomor/macOS-ansible.git"
    repo_ssh: "git@github.com:gperdomor/macOS-ansible.git"
