---
- name: Mac setup
  hosts: localhost
  connection: local

  vars_files:
    - config.yml
    - config.local.yml

  pre_tasks:
    - name: Ensure host is running macOS
      fail: msg="The host (target) system is not running macOS."
      when: ansible_os_family != "Darwin"
      tags: always

  roles:

    # Prep
    # --------------------------------------------------------------------------

    - { role: danbohea.spelling, tags: ["spelling","prep"] }

    # Stage 1: Essential day-to-day
    # --------------------------------------------------------------------------

    - { role: danbohea.flux, tags: ["flux","stage_1"] }
    - { cask_app_name: "the-unarchiver", tags: ["the_unarchiver","stage_1"], role: danbohea.cask-app }
    - { cask_app_name: "firefox", tags: ["firefox","stage_1"], role: danbohea.cask-app }

    # Last
    # --------------------------------------------------------------------------

    - { role: danbohea.dock-items, tags: ["dock_items","last","always"] }

  post_tasks:

    - debug:
        msg: "Some changes may not take effect until you've restarted your Mac."
      tags: always
