---
- import_tasks: hostname.yml
  tags: [settings-hostname]

- import_tasks: safari.yml
  tags: [settings-safari]

- import_tasks: system.yml
  tags: [settings-system]

- import_tasks: dock.yml
  tags: [settings-dock]

- import_tasks: finder.yml
  tags: [settings-finder]

- import_tasks: trackpad_tap_to_click.yml
  when: trackpad_tap_to_click != None
  tags: [settings-trackpad]

- import_tasks: transmission.yml
  when: '"transmission" in homebrew_apps'
  tags: [settings-transmission]

- import_tasks: tower.yml
  when: '"tower" in homebrew_apps'
  tags: [settings-tower]

- import_tasks: ssh.yml
  when: configure_ssh
  tags: [settings-ssh]
