---
- name: Restart Dock
  command: killall Dock
  register: dock_output
  changed_when: dock_output.rc != 0

- name: Restart Finder
  command: killall Finder
  register: finder_output
  changed_when: finder_output.rc != 0
