---
- name: Restart Finder
  command: killall Finder

- name: Restart Dock
  command: killall Dock

- name: Restart Safari
  command: osascript -e 'quit app "Safari"' && osascript -e 'tell application "Safari" to activate'

- name: Restart Transmission
  command: killall Transmission
  ignore_errors: true

- name: Restart Tower
  command: killall Tower
  ignore_errors: true
