name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Test on macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies.
        run: bash scripts/install_deps.sh
      - name: Copy starter files
        run: bash scripts/copy_starter_files.sh
      - name: Install dependencies
        run: ansible-galaxy install -r custom/requirements.yml --force
      - name: Checking the role/playbook's syntax
        run: ansible-playbook macsible.yml --syntax-check
      - name: Run playbook
        run: ansible-playbook macsible.yml --skip-tags "no_ci"
