name: CI for macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  playbook:
    runs-on: macos-latest
    name: Tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip3 install ansible
          ansible-galaxy install -r requirements.yml --force
      - name: Checking the playbook's syntax
        run: ansible-playbook main.yml --syntax-check
      - name: Copy test config.yml into place
        run: cp tests/config.yml config.yml
      - name: Run playbook
        run: ansible-playbook main.yml -i hosts
      # - name: Test the playbook's idempotence
      #   run: |
      #     idempotence=$(mktemp)
      #     ansible-playbook main.yml -i hosts | tee -a ${idempotence}
      #     tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
