---
name: CI for macOS

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 5 1,15 1-12 *"

jobs:
  lint:
    name: Lint
    runs-on: macos-15
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install test dependencies.
        run: pip3 install yamllint ansible ansible-lint

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint

  playbook:
    name: Playbook
    runs-on: macos-15
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # - name: Uninstall GitHub Actions' built-in browser installs.
      #   run: |
      #     sudo rm -rf /Applications/Firefox.app
      #     sudo rm -rf /Applications/Google\ Chrome.app

      - name: Install test dependencies.
        run: sudo pip3 install ansible

      - name: Set up the test environment.
        run: |
          ansible-galaxy install -r requirements.yml
      #     cp tests/ansible.cfg ./ansible.cfg
      #     cp tests/inventory.yml ./inventory.yml
      #     cp tests/config.yml ./config.yml

      - name: Test the playbook's syntax.
        run: ansible-playbook bootstrap.yml --syntax-check

      - name: Test the playbook.
        run: ansible-playbook bootstrap.yml
        env:
          ANSIBLE_FORCE_COLOR: "1"

      - name: Idempotence check.
        run: |
          idempotence=$(mktemp)
          ansible-playbook bootstrap.yml | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: "1"
