---
name: CI for macOS

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 5 1,15 1-12 *"

jobs:
  lint:
    name: Lint
    runs-on: macos-15
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.12.2
        with:
          requirements_file: requirements.yml

  playbook:
    name: Playbook
    runs-on: macos-15
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install test dependencies.
        run: brew install ansible

      - name: Set up the test environment.
        run: |
          cp tests/config.yml ./config.yml
          ansible-galaxy install -r requirements.yml

      - name: Test the playbook's syntax.
        run: ansible-playbook bootstrap.yml --syntax-check

      - name: Test the playbook.
        run: ansible-playbook bootstrap.yml -t "homebrew,shell,node"
        env:
          ANSIBLE_FORCE_COLOR: "1"

      - name: Idempotence check.
        run: |
          idempotence=$(mktemp)
          ansible-playbook bootstrap.yml -t "homebrew,shell,node" | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: "1"
