---

- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo_https }}"
    dest: "{{ dotfiles_dir }}"
    version: master
    accept_hostkey: yes

# Command uses `basename` to return only filenames (excludes paths)
# Source: http://superuser.com/a/620591
- name: Get list of filenames to symlink to
  command: find . -type f -depth 1 -name ".*" -exec basename {} \;
  args:
    chdir: "{{ dotfiles_dir }}"
  register: dotfiles_to_symlink
  changed_when: false

- name: Create symlinks to files in dotfiles directory
  file:
    path: ~/{{ item }}
    src: "{{ dotfiles_dir }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ dotfiles_to_symlink.stdout_lines }}"

# TODO: Make idempotent
- name: Set git remote URL to SSH
  shell: git remote set-url origin {{ dotfiles_repo_ssh }}
  args:
    chdir: "{{ dotfiles_dir }}"
    warn: false
